% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
  \usepackage{amssymb}
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={COSC6323 - Exercise 6},
  pdfauthor={Sachin Shubham},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{COSC6323 - Exercise 6}
\author{Sachin Shubham}
\date{3/13/2021}

\begin{document}
\maketitle

1 Task One aspect of wildlife science is the study of how various habits
of wildlife are affected by environmental conditions. In this exercise,
we are concerned about the effect of air temperature on the time that
the ''lesser snow geese'' leave their overnight roost sites to fly to
their feeding areas. The data is given in Geese.txt. 1. Obtain the
necessary plots. 2. Compute the LM coefficients for the 'time vs temp'
model (β0 , β1). 3. Obtain the regression equation. 4. Obtain the
confidence intervals for β1. 5. Is there correlation between the
temperature and time in the Geese data set?

Solution:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{filepath }\OtherTok{=} \StringTok{\textquotesingle{}C:}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{Users}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{sachi}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{Downloads}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{Geese.txt\textquotesingle{}}


\NormalTok{geese }\OtherTok{\textless{}{-}} \FunctionTok{read.table}\NormalTok{(filepath,          }\CommentTok{\# TXT data file indicated as string or full path to the file}
                    \AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{,    }\CommentTok{\# Whether to display the header (TRUE) or not (FALSE)}
                    \AttributeTok{sep =} \StringTok{""}\NormalTok{,          }\CommentTok{\# Separator of the columns of the file}
                    \AttributeTok{dec =} \StringTok{"."}\NormalTok{)         }\CommentTok{\# Character used to separate decimals of the numbers in the file}

\CommentTok{\# PREDICTOR (temprature)}
\NormalTok{temp}\OtherTok{\textless{}{-}}\NormalTok{geese}\SpecialCharTok{$}\NormalTok{temp}

\CommentTok{\# RESPONCE (time)}
\NormalTok{time}\OtherTok{\textless{}{-}}\NormalTok{geese}\SpecialCharTok{$}\NormalTok{time}

\CommentTok{\# Apply the lm() function.}
\NormalTok{model }\OtherTok{=} \FunctionTok{lm}\NormalTok{(temp }\SpecialCharTok{\textasciitilde{}}\NormalTok{ time, }\AttributeTok{data =} \FunctionTok{data.frame}\NormalTok{(geese) )}

\CommentTok{\#1 Plot}
\CommentTok{\# Plot the chart.}
\FunctionTok{plot}\NormalTok{(time,temp,}\AttributeTok{col =} \StringTok{"blue"}\NormalTok{,}\AttributeTok{main =} \StringTok{"Effect of Air Temperature on Lesser Snow Geese Leaving Roost"}\NormalTok{,}
     \FunctionTok{abline}\NormalTok{(}\FunctionTok{lm}\NormalTok{(temp}\SpecialCharTok{\textasciitilde{}}\NormalTok{time)), }\AttributeTok{cex =} \FloatTok{1.3}\NormalTok{, }\AttributeTok{pch =} \DecValTok{16}\NormalTok{,}
     \AttributeTok{xlab =} \StringTok{"Air Temperature"}\NormalTok{,}
     \AttributeTok{ylab =} \StringTok{"Lesser Snow Geese Response Time"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Sachin_Shubham_files/figure-latex/unnamed-chunk-1-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Sachin_Shubham_files/figure-latex/unnamed-chunk-1-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#2  LM coefficients for the ’time vs temp’ model (β0 , β1)}
\FunctionTok{lm}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ temp, }\AttributeTok{data =}\NormalTok{ geese)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = time ~ temp, data = geese)
## 
## Coefficients:
## (Intercept)         temp  
##     -19.667        1.681
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#3 The regression equation}
\FunctionTok{lm}\NormalTok{(temp }\SpecialCharTok{\textasciitilde{}}\NormalTok{ time, }\AttributeTok{data =} \FunctionTok{data.frame}\NormalTok{(geese))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = temp ~ time, data = data.frame(geese))
## 
## Coefficients:
## (Intercept)         time  
##     10.5137       0.3523
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#4 Confidence intervals for β1}
\FunctionTok{confint}\NormalTok{(model, }\StringTok{\textquotesingle{}time\textquotesingle{}}\NormalTok{, }\AttributeTok{level=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          2.5 %    97.5 %
## time 0.2534182 0.4511043
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#5 Is there correlation between the temperature and time in the Geese data set?}
\NormalTok{correlation\_coeff}\OtherTok{\textless{}{-}}\FunctionTok{cor}\NormalTok{(time,temp)}
\NormalTok{correlation\_coeff}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7694334
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{summary}\NormalTok{(model))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = temp ~ time, data = data.frame(geese))
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.6388 -2.9401 -0.2408  1.6338 13.3612 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 10.51370    0.77714  13.529 1.10e-15 ***
## time         0.35226    0.04874   7.228 1.65e-08 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.559 on 36 degrees of freedom
## Multiple R-squared:  0.592,  Adjusted R-squared:  0.5807 
## F-statistic: 52.24 on 1 and 36 DF,  p-value: 1.653e-08
\end{verbatim}

Our study shows that Multiple R-squared is approx 60\%(0.592) and
p-value is 1.653e-08.

The 0.7694334 Correlation Coefficient indicate a strong positive linear
relationship.

The fitted β1 is 0.35226 with an interval of (0.2534182, 0.4511043).

As p-value(1.653e-08) is less than 0.05, therefore relationship between
time and temperature is statistically significant.It indicates strong
evidence against the null hypothesis, as there is less than a 5\%
probability the null is correct. Therefore, we reject the null
hypothesis, and accept the alternative hypothesis.

\end{document}
